# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: AuxiliaryData.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='AuxiliaryData.proto',
  package='volva.proto',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=b'\n\x13\x41uxiliaryData.proto\x12\x0bvolva.proto\"J\n\rAuxiliaryData\x12\n\n\x02id\x18\x01 \x02(\x0c\x12\x0c\n\x04kind\x18\x02 \x02(\t\x12\x10\n\x08referent\x18\x03 \x02(\x0c\x12\r\n\x05value\x18\x04 \x01(\x0c'
)




_AUXILIARYDATA = _descriptor.Descriptor(
  name='AuxiliaryData',
  full_name='volva.proto.AuxiliaryData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='volva.proto.AuxiliaryData.id', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='kind', full_name='volva.proto.AuxiliaryData.kind', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='referent', full_name='volva.proto.AuxiliaryData.referent', index=2,
      number=3, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='volva.proto.AuxiliaryData.value', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=110,
)

DESCRIPTOR.message_types_by_name['AuxiliaryData'] = _AUXILIARYDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AuxiliaryData = _reflection.GeneratedProtocolMessageType('AuxiliaryData', (_message.Message,), {
  'DESCRIPTOR' : _AUXILIARYDATA,
  '__module__' : 'AuxiliaryData_pb2'
  # @@protoc_insertion_point(class_scope:volva.proto.AuxiliaryData)
  })
_sym_db.RegisterMessage(AuxiliaryData)


# @@protoc_insertion_point(module_scope)
