# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Block.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Block.proto',
  package='volva.proto',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=b'\n\x0b\x42lock.proto\x12\x0bvolva.proto\"f\n\x05\x42lock\x12\n\n\x02id\x18\x01 \x02(\x0c\x12\x0e\n\x06offset\x18\x02 \x02(\x04\x12%\n\x04kind\x18\x03 \x02(\x0e\x32\x17.volva.proto.Block.Kind\"\x1a\n\x04Kind\x12\x08\n\x04\x43ode\x10\x00\x12\x08\n\x04\x44\x61ta\x10\x01\"q\n\nBlockGroup\x12\n\n\x02id\x18\x01 \x02(\x0c\x12\"\n\x06\x62locks\x18\x02 \x03(\x0b\x32\x12.volva.proto.Block\x12\x14\n\x0c\x62\x61se_address\x18\x03 \x01(\x04\x12\x0c\n\x04size\x18\x04 \x02(\x04\x12\x0f\n\x07\x62\x61\x63king\x18\x05 \x02(\x0c'
)



_BLOCK_KIND = _descriptor.EnumDescriptor(
  name='Kind',
  full_name='volva.proto.Block.Kind',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Code', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Data', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=104,
  serialized_end=130,
)
_sym_db.RegisterEnumDescriptor(_BLOCK_KIND)


_BLOCK = _descriptor.Descriptor(
  name='Block',
  full_name='volva.proto.Block',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='volva.proto.Block.id', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='offset', full_name='volva.proto.Block.offset', index=1,
      number=2, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='kind', full_name='volva.proto.Block.kind', index=2,
      number=3, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _BLOCK_KIND,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=130,
)


_BLOCKGROUP = _descriptor.Descriptor(
  name='BlockGroup',
  full_name='volva.proto.BlockGroup',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='volva.proto.BlockGroup.id', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='blocks', full_name='volva.proto.BlockGroup.blocks', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='base_address', full_name='volva.proto.BlockGroup.base_address', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='size', full_name='volva.proto.BlockGroup.size', index=3,
      number=4, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='backing', full_name='volva.proto.BlockGroup.backing', index=4,
      number=5, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=132,
  serialized_end=245,
)

_BLOCK.fields_by_name['kind'].enum_type = _BLOCK_KIND
_BLOCK_KIND.containing_type = _BLOCK
_BLOCKGROUP.fields_by_name['blocks'].message_type = _BLOCK
DESCRIPTOR.message_types_by_name['Block'] = _BLOCK
DESCRIPTOR.message_types_by_name['BlockGroup'] = _BLOCKGROUP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Block = _reflection.GeneratedProtocolMessageType('Block', (_message.Message,), {
  'DESCRIPTOR' : _BLOCK,
  '__module__' : 'Block_pb2'
  # @@protoc_insertion_point(class_scope:volva.proto.Block)
  })
_sym_db.RegisterMessage(Block)

BlockGroup = _reflection.GeneratedProtocolMessageType('BlockGroup', (_message.Message,), {
  'DESCRIPTOR' : _BLOCKGROUP,
  '__module__' : 'Block_pb2'
  # @@protoc_insertion_point(class_scope:volva.proto.BlockGroup)
  })
_sym_db.RegisterMessage(BlockGroup)


# @@protoc_insertion_point(module_scope)
