# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ICFG.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ICFG.proto',
  package='volva.proto',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=b'\n\nICFG.proto\x12\x0bvolva.proto\"\xf7\x01\n\x04ICFG\x12%\n\x05\x65\x64ges\x18\x01 \x03(\x0b\x32\x16.volva.proto.ICFG.Edge\x12\r\n\x05nodes\x18\x02 \x03(\x0c\x1a\xb8\x01\n\x04\x45\x64ge\x12\x0e\n\x06source\x18\x01 \x02(\x0c\x12\x13\n\x0b\x64\x65stination\x18\x02 \x02(\x0c\x12)\n\x04kind\x18\x03 \x02(\x0e\x32\x1b.volva.proto.ICFG.Edge.Kind\x12\x13\n\x0b\x63onditional\x18\x04 \x02(\x08\x12\x10\n\x08indirect\x18\x05 \x02(\x08\"9\n\x04Kind\x12\n\n\x06\x42ranch\x10\x00\x12\x08\n\x04\x43\x61ll\x10\x01\x12\x0f\n\x0b\x46\x61llthrough\x10\x02\x12\n\n\x06Return\x10\x03'
)



_ICFG_EDGE_KIND = _descriptor.EnumDescriptor(
  name='Kind',
  full_name='volva.proto.ICFG.Edge.Kind',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Branch', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Call', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Fallthrough', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Return', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=218,
  serialized_end=275,
)
_sym_db.RegisterEnumDescriptor(_ICFG_EDGE_KIND)


_ICFG_EDGE = _descriptor.Descriptor(
  name='Edge',
  full_name='volva.proto.ICFG.Edge',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='source', full_name='volva.proto.ICFG.Edge.source', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='destination', full_name='volva.proto.ICFG.Edge.destination', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='kind', full_name='volva.proto.ICFG.Edge.kind', index=2,
      number=3, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='conditional', full_name='volva.proto.ICFG.Edge.conditional', index=3,
      number=4, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='indirect', full_name='volva.proto.ICFG.Edge.indirect', index=4,
      number=5, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _ICFG_EDGE_KIND,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=91,
  serialized_end=275,
)

_ICFG = _descriptor.Descriptor(
  name='ICFG',
  full_name='volva.proto.ICFG',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='edges', full_name='volva.proto.ICFG.edges', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nodes', full_name='volva.proto.ICFG.nodes', index=1,
      number=2, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_ICFG_EDGE, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=275,
)

_ICFG_EDGE.fields_by_name['kind'].enum_type = _ICFG_EDGE_KIND
_ICFG_EDGE.containing_type = _ICFG
_ICFG_EDGE_KIND.containing_type = _ICFG_EDGE
_ICFG.fields_by_name['edges'].message_type = _ICFG_EDGE
DESCRIPTOR.message_types_by_name['ICFG'] = _ICFG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ICFG = _reflection.GeneratedProtocolMessageType('ICFG', (_message.Message,), {

  'Edge' : _reflection.GeneratedProtocolMessageType('Edge', (_message.Message,), {
    'DESCRIPTOR' : _ICFG_EDGE,
    '__module__' : 'ICFG_pb2'
    # @@protoc_insertion_point(class_scope:volva.proto.ICFG.Edge)
    })
  ,
  'DESCRIPTOR' : _ICFG,
  '__module__' : 'ICFG_pb2'
  # @@protoc_insertion_point(class_scope:volva.proto.ICFG)
  })
_sym_db.RegisterMessage(ICFG)
_sym_db.RegisterMessage(ICFG.Edge)


# @@protoc_insertion_point(module_scope)
