# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Image.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import AuxiliaryData_pb2 as AuxiliaryData__pb2
from . import ICFG_pb2 as ICFG__pb2
from . import Module_pb2 as Module__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='Image.proto',
  package='volva.proto',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=b'\n\x0bImage.proto\x12\x0bvolva.proto\x1a\x13\x41uxiliaryData.proto\x1a\nICFG.proto\x1a\x0cModule.proto\"\x93\x01\n\x05Image\x12\n\n\x02id\x18\x01 \x02(\x0c\x12$\n\x07modules\x18\x02 \x03(\x0b\x32\x13.volva.proto.Module\x12$\n\tinter_cfg\x18\x03 \x02(\x0b\x32\x11.volva.proto.ICFG\x12\x32\n\x0e\x61uxiliary_data\x18\x04 \x03(\x0b\x32\x1a.volva.proto.AuxiliaryData'
  ,
  dependencies=[AuxiliaryData__pb2.DESCRIPTOR,ICFG__pb2.DESCRIPTOR,Module__pb2.DESCRIPTOR,])




_IMAGE = _descriptor.Descriptor(
  name='Image',
  full_name='volva.proto.Image',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='volva.proto.Image.id', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='modules', full_name='volva.proto.Image.modules', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='inter_cfg', full_name='volva.proto.Image.inter_cfg', index=2,
      number=3, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='auxiliary_data', full_name='volva.proto.Image.auxiliary_data', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=76,
  serialized_end=223,
)

_IMAGE.fields_by_name['modules'].message_type = Module__pb2._MODULE
_IMAGE.fields_by_name['inter_cfg'].message_type = ICFG__pb2._ICFG
_IMAGE.fields_by_name['auxiliary_data'].message_type = AuxiliaryData__pb2._AUXILIARYDATA
DESCRIPTOR.message_types_by_name['Image'] = _IMAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Image = _reflection.GeneratedProtocolMessageType('Image', (_message.Message,), {
  'DESCRIPTOR' : _IMAGE,
  '__module__' : 'Image_pb2'
  # @@protoc_insertion_point(class_scope:volva.proto.Image)
  })
_sym_db.RegisterMessage(Image)


# @@protoc_insertion_point(module_scope)
