# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Machine.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Machine.proto',
  package='volva.proto',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=b'\n\rMachine.proto\x12\x0bvolva.proto*d\n\x0c\x41rchitecture\x12\x07\n\x03\x41RM\x10\x00\x12\n\n\x06\x41RM_64\x10\x01\x12\x08\n\x04MIPS\x10\x02\x12\x0b\n\x07MIPS_64\x10\x03\x12\x07\n\x03PPC\x10\x04\x12\n\n\x06PPC_64\x10\x05\x12\x07\n\x03X86\x10\x06\x12\n\n\x06X86_64\x10\x07*\x1d\n\x06\x45ndian\x12\x07\n\x03\x42ig\x10\x00\x12\n\n\x06Little\x10\x01'
)

_ARCHITECTURE = _descriptor.EnumDescriptor(
  name='Architecture',
  full_name='volva.proto.Architecture',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ARM', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ARM_64', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MIPS', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MIPS_64', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PPC', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PPC_64', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='X86', index=6, number=6,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='X86_64', index=7, number=7,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=30,
  serialized_end=130,
)
_sym_db.RegisterEnumDescriptor(_ARCHITECTURE)

Architecture = enum_type_wrapper.EnumTypeWrapper(_ARCHITECTURE)
_ENDIAN = _descriptor.EnumDescriptor(
  name='Endian',
  full_name='volva.proto.Endian',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Big', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Little', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=132,
  serialized_end=161,
)
_sym_db.RegisterEnumDescriptor(_ENDIAN)

Endian = enum_type_wrapper.EnumTypeWrapper(_ENDIAN)
ARM = 0
ARM_64 = 1
MIPS = 2
MIPS_64 = 3
PPC = 4
PPC_64 = 5
X86 = 6
X86_64 = 7
Big = 0
Little = 1


DESCRIPTOR.enum_types_by_name['Architecture'] = _ARCHITECTURE
DESCRIPTOR.enum_types_by_name['Endian'] = _ENDIAN
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


# @@protoc_insertion_point(module_scope)
