# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Symbol.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Symbol.proto',
  package='volva.proto',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=b'\n\x0cSymbol.proto\x12\x0bvolva.proto\"\xd3\x01\n\x06Symbol\x12\n\n\x02id\x18\x01 \x02(\x0c\x12\x0c\n\x04name\x18\x02 \x02(\t\x12\x15\n\x0breferent_id\x18\x03 \x01(\x0cH\x00\x12\x1a\n\x10referent_address\x18\x04 \x01(\x04H\x00\x12&\n\x04kind\x18\x05 \x02(\x0e\x32\x18.volva.proto.Symbol.Kind\"H\n\x04Kind\x12\x0c\n\x08\x46unction\x10\x00\x12\x0c\n\x08Variable\x10\x01\x12\x0e\n\nAnnotation\x10\x02\x12\t\n\x05Label\x10\x03\x12\t\n\x05Other\x10\x04\x42\n\n\x08referent'
)



_SYMBOL_KIND = _descriptor.EnumDescriptor(
  name='Kind',
  full_name='volva.proto.Symbol.Kind',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Function', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Variable', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Annotation', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Label', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Other', index=4, number=4,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=157,
  serialized_end=229,
)
_sym_db.RegisterEnumDescriptor(_SYMBOL_KIND)


_SYMBOL = _descriptor.Descriptor(
  name='Symbol',
  full_name='volva.proto.Symbol',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='volva.proto.Symbol.id', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='volva.proto.Symbol.name', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='referent_id', full_name='volva.proto.Symbol.referent_id', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='referent_address', full_name='volva.proto.Symbol.referent_address', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='kind', full_name='volva.proto.Symbol.kind', index=4,
      number=5, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _SYMBOL_KIND,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='referent', full_name='volva.proto.Symbol.referent',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=30,
  serialized_end=241,
)

_SYMBOL.fields_by_name['kind'].enum_type = _SYMBOL_KIND
_SYMBOL_KIND.containing_type = _SYMBOL
_SYMBOL.oneofs_by_name['referent'].fields.append(
  _SYMBOL.fields_by_name['referent_id'])
_SYMBOL.fields_by_name['referent_id'].containing_oneof = _SYMBOL.oneofs_by_name['referent']
_SYMBOL.oneofs_by_name['referent'].fields.append(
  _SYMBOL.fields_by_name['referent_address'])
_SYMBOL.fields_by_name['referent_address'].containing_oneof = _SYMBOL.oneofs_by_name['referent']
DESCRIPTOR.message_types_by_name['Symbol'] = _SYMBOL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Symbol = _reflection.GeneratedProtocolMessageType('Symbol', (_message.Message,), {
  'DESCRIPTOR' : _SYMBOL,
  '__module__' : 'Symbol_pb2'
  # @@protoc_insertion_point(class_scope:volva.proto.Symbol)
  })
_sym_db.RegisterMessage(Symbol)


# @@protoc_insertion_point(module_scope)
